### ISSUE TITLE
Siphon not working

### ISSUE THREAD

**Issue by astessss** [strikerrocker/VanillaTweaks#196] opened 2023-07-21 19:15 UTC
MC Version: 1.20.1 (Fabric)
Mod Version: 1.5.69

**Comment by lospejos** [comment] 2023-07-23 22:50
I've tested this mod on `Minecraft 1.20.1` with mods:

```
architectury-9.1.10-fabric (required by Roughly Enough Items)
cloth-config-11.1.106-fabric (required by Vanilla Tweaks)
fabric-api-0.86.0+1.20.1
RoughlyEnoughItems-12.0.634
VanillaTweaks-fabric-1.20.1-1.5.69
```

and `Siphon` enchantment works just fine.

However, on my mega huge build (200+ jar files in `mods` folder, `Minecraft` reports `371 mods loaded` when started) this enchantment is not working. No error or warning messages with text containing `siphon` present in log files.

I assume it has some kind of conflicts with other mods.

**Comment by lospejos** [comment] 2023-07-23 23:07
I also added logging `Siphon` events in
```
VanillaTweaks/common/src/main/java/io/github/strikerrocker/vt/enchantments/EnchantmentImpl.java
```

in method

```
public static List<ItemStack> siphonLogic(Entity entity, List<ItemStack> dropList)
```

In _quasi-vanilla_ Minecraft (with minimal mods installed, see above) this log record appears in log file.

In my huge build (200+ jar files in `mods` folder) log does not contain this record. This means that this method not executed, probably due to a mods conflict (probably).

**Comment by lospejos** [comment] 2023-07-23 23:24
I also tried to disable mods, containing `getDrops` in their `*.refmap.json` files (I found one mod among bunch of mods in my build, this was `Fish Of Thieves` mod). But `Siphon` enchantment still was not working.

I hope this information will be helpful to mod's author.

**Comment by lospejos** [comment] 2023-07-24 11:57
After upgrading my Minecraft mega build (`215 jar files` in `mods` directory, Minecraft Fabric reports `385 mods`), `Siphon` enchantment works just fine.

I'm not sure, what exact mod was the cause.

Updated mods list:

```
cupboard-fabric-1.20.1-1.2.jar
Patchouli-1.20.1-81-FABRIC.jar
FactoryAPI-1.20.1-0.1.9-fabric.jar
FallingTree-1.20.1-4.2.3.jar
PuzzlesLib-v8.0.12-1.20.1-Fabric.jar
```

The full mods list is:

```
(Fabric)SimpleMango-1.20.x-1.3.2.jar
ACE-2.0.5.jar
actuallyunbreaking-1.20-0.1.0.jar
AdditionalStructures-1.20.x-(v.4.2.0).jar
adorabuild-structures-1.20.1-fabric-1.0.0.jar
advancednetherite-fabric-2.0.2-1.20.1.jar
adventurez-1.4.18.jar
allarrowsinfinityfix-1.5-fabric-mc1.20.jar
alloy-forgery-2.0.22+1.20.jar
AmbientSounds_FABRIC_v5.2.20_mc1.20.1.jar
amecs-1.3.9+mc.1.20-pre2.jar
amethyst-tools-v1.0_fabric+quilt_mc1.20.0.jar
antighost-1.20-fabric0.83.0-1.1.5.jar
appleskin-fabric-mc1.20-2.5.0.jar
architectury-9.1.10-fabric.jar
areas-1.20.1-5.0.jar
armorpointspp-fabric-1.20-3.1.1.jar
armorskin-0.2.jar
authme-7.0.2+1.20.jar
auto-clicker-fabric-1.20.1-1.6.2-build.9999.jar
autofish-0.9.11.jar
AxesAreWeapons-1.7.0-fabric-1.19.3.jar
axolotl-item-fix-1.1.7.jar
axolotlbuckets-1.2.0+1.20.jar
azure-paxels-1.20.1-1.0.5.jar
azurelib-fabric-1.20.1-1.0.19.jar
bclib-3.0.12.jar
better-end-4.0.9.jar
better-nether-9.0.9.jar
BetterAdvancements-Fabric-1.20.1-0.3.2.161.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
BetterFurnaces-1.20.1-1.0.1-fabric.jar
biomemakeover-FABRIC-1.20.1-1.10.2.jar
Boat-Item-View-Fabric-1.20.1-0.0.5.jar
BOMD-1.7-1.20.jar
Bookshelf-Fabric-1.20.1-20.0.1.jar
c2me-fabric-mc1.20.1-0.2.0+alpha.10.94.jar
cardinal-components-api-5.2.1.jar
castle_dungeons-4.0.0-1.20-fabric.jar
CatEyes-v7_Fabric-1.20.1.jar
cbp-1.0.5.1.jar
cherish-1.2.0.jar
cherishedworlds-fabric-6.1.1+1.20.1.jar
cloth-config-11.1.106-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
collective-1.20.1-6.65.jar
connectedglass-1.1.7-fabric-mc1.20.jar
continuity-3.0.0-beta.3+1.20.1.jar
cooldown-coordinator-0.6.2.jar
copperhopper-0.4.0+1.20.1.jar
CorgiLib-fabric-1.20.1-4.0.0.0.jar
CreativeCore_FABRIC_v2.10.28_mc1.20.1.jar
CreoLib-1.20.1-1.0.0-beta.21.jar
crystals_overhauled_v1.2.3_1.20.1_FABRIC.jar
ctov-3.3.2.jar
CullLessLeaves-1.2.0.jar
cupboard-fabric-1.20.1-1.2.jar
dark-loading-screen-1.6.14.jar
dawn-5.0.0.jar
Debugify-1.20.1+2.0.jar
disenchanter-0.1.7+1.20.jar
disintegrator-1.0.4.jar
doubledoors-1.20.1-5.0.jar
dualwield-4.0-1.20.1.jar
dungeons-and-taverns-v2.1.4.jar
durabilitytooltip-1.1.4-fabric-mc1.20.jar
dusk-fabric-1.20.1-3.3.jar
dynamic-fps-2.4.0.jar
dynamiccrosshair-7.0.4+1.20-fabric.jar
dynamiccrosshair-compat-3.2+1.20.1.jar
EasyAnvils-v8.0.0-1.20.1-Fabric.jar
EasyHopper-fabric-mc1.20.1-2.6.2.jar
EasyMagic-v8.0.1-1.20.1-Fabric.jar
enchantmentcompat-1.2.1+1.20.jar
EnchantmentDescriptions-Fabric-1.20.1-17.0.2.jar
entityculling-fabric-1.6.2-mc1.20.jar
entity_texture_features_fabric_1.20-4.4.4.jar
extended-copper-1.4.2-1.20.jar
extra-damage-enchantments-1.1.0.jar
fabric-api-0.86.0+1.20.1.jar
fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
fabrication-3.3.4+1.20.jar
FactoryAPI-1.20.1-0.1.9-fabric.jar
fallingleaves-1.15.2+1.20.1.jar
FallingTree-1.20.1-4.2.3.jar
Fastload+1.18.2-1.20-3.4.0.jar
ferritecore-6.0.0-fabric.jar
fish_of_thieves-mc1.20.1-v3.0.2-fabric.jar
ForbiddenPotions-1.1.0-1.20.x.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
friendsandfoes-fabric-mc1.20.1-1.9.3.jar
frogson-1.14.0.beta9.jar
frogvasion-2.1-fabric.jar
fullturtlearmor-1.5-fabric-mc1.20.1.jar
geckolib-fabric-1.20.1-4.2.1.jar
grind-enchantments-3.1.2+1.20.jar
HWGMod-1.20.1-1.4.14.jar
IllagersWearArmor-1.1.0+1.20.jar
ImmediatelyFast-1.1.16+1.20.1.jar
imst-2.1.0.jar
imst_n-1.1.0.jar
Incendium_1.20.1_v5.3.1.jar
indium-1.0.21+mc1.20.1.jar
Infinitory-1.5.0-pre.4+1.20.jar
InventoryProfilesNext-fabric-1.20-1.10.6.jar
iris-mc1.20-1.6.4.jar
ironbookshelves-1.20.1-1.1.0-fabric.jar
Jade-1.20-fabric-11.3.0.jar
jamlib-0.6.0+1.20.jar
knavesneeds-fabric-1.1.5+1.20.1.jar
krypton-0.2.3.jar
lambdynamiclights-2.3.1+1.20.1.jar
language-reload-1.5.8+1.20.1.jar
libIPN-fabric-1.20-3.0.2.jar
light-overlay-8.0.0.jar
lithium-fabric-mc1.20.1-0.11.2.jar
lunade-fastanim-1.6-1.20.jar
malilib-fabric-1.20.1-0.16.1.jar
MCDoom-Fabric-1.20.1-6.0.2.jar
mcpitanlibarch-1.7.5-1.20.1-fabric.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
mes-1.1-1.20-fabric.jar
midnightlib-fabric-1.4.1.1.jar
mine-treasure-1.2.9.jar
minecraft-comes-alive-7.5.3+1.20.1-universal.jar
mixintrace-1.1.1+1.17.jar
modernfix-fabric-5.3.2+mc1.20.1.jar
modmenu-7.2.1.jar
moonlight-1.20-2.7.2-fabric.jar
more-amethyst-recipes-1.0.jar
MoreBows-1.0.11+1.20.x.jar
moremobvariants-fabric+1.20-1.2.2.jar
moreswordsmod-0.0.2-1.20.1.jar
mru-0.2.1+1.20.jar
Multitool-v4.1.2.jar
MutantMonsters-v8.0.2-1.20.1-Fabric.jar
mvs-4.0-1.20-fabric.jar
mythic-mounts-1.20.1-7.2.jar
mythicmetals-0.18.0+1.20.jar
mythicupgrades-1.9.0-1.20.1.jar
newworld-fabric-1.20.1-1.3.0.jar
no-shield-delay-1.0.0.jar
nyfsspiders-fabric-1.20.1-2.1.0.jar
obsidian_slab-1.2.0.jar
omnihopper-2.2.0+1.20.jar
owo-lib-0.11.1+1.20.jar
Patchouli-1.20.1-81-FABRIC.jar
Philips-Ruins1.20.1-1.5[Fabric].jar
Ping-Wheel-1.4.0-fabric-1.20.1.jar
plenty-of-armors-1.2.1+mc1.20.1.jar
polymer-bundled-0.5.5+1.20.1.jar
promenade-4.1.0.jar
Pumped+Desert+2+Fabric+1.20.jar
PuzzlesLib-v8.0.12-1.20.1-Fabric.jar
qu-enchantments-1.3.5-1.20.jar
reeses_sodium_options-1.5.1+mc1.20-build.74.jar
RegionsUnexploredFabric-0.4.1+1.20.1.jar
reinforced-upgrade-1.0.1-1.20.1.jar
repurposed_structures-7.0.0+1.20-fabric.jar
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric.jar
RoughlyEnoughItems-12.0.634.jar
Rrls-1.20.1-3.1.0-fabric.jar
saplanting-fabric-1.20-1.2.4.jar
satin-1.13.0.jar
servercore-fabric-1.3.7+1.20.1.jar
showdurability-1.1.0+1.20.1.jar
simplyswords-fabric-1.48.1-1.21.jar
skeletonhorsespawn-1.20.1-3.6.jar
SmartBrainLib-fabric-1.20-1.11.jar
Soaring-Structures-2-1.20.1-2.5-FABRIC.jar
sodium-extra-0.4.23+mc1.20.1-build.106.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
soundphysics-fabric-1.20.1-1.1.1.jar
spark-1.10.42-fabric.jar
Species-1.20.1-1.3-Fabric.jar
spellbound-weapons-v4.0.5f.jar
spoornarmorattributes-3.0-1.20.1-fabric.jar
spoornweaponattributes-5.0-1.20.1-fabric.jar
stendhal-1.3.9-1.20.jar
strange-berries-2.2.1-1.20.x.jar
subterrestrial-fabric-1.20-2.2.0.jar
supermartijn642configlib-1.1.7-fabric-mc1.20.jar
supermartijn642corelib-1.1.12-fabric-mc1.20.jar
TerraBlender-fabric-1.20.1-3.0.0.169.jar
Terralith_1.20.1_v2.4.3.jar
terrestria-6.0.8.jar
TheOffcialOvergrownMod6.4.9.jar
ToolStats-Fabric-1.20.1-16.0.1.jar
tooltipfix-1.1.1-1.20.jar
tooltiprareness-1.0.9.jar
travelers-backpack-1.20.1-9.1.2.jar
traverse-7.0.8.jar
treeharvester-1.20.1-8.2.jar
trinkets-3.7.1.jar
tropics-1.0.2.jar
tweakermore-mc1.20.1-v3.14.0.jar
UncraftingTable-fabric-1.2.6.jar
UniversalEnchants-v8.0.0-1.20.1-Fabric.jar
VanillaTweaks-fabric-1.20.1-1.5.69.jar
vanilla_degus-1.20.x-v1.4.1-fabric.jar
veinmining-fabric-1.2.0+1.20.1.jar
villagernames-1.20.1-5.2.jar
VillagersPlus_2.0_(FABRIC)_for_1.20.1.jar
visuality-0.7.0+1.20.jar
voicechat-fabric-1.20.1-2.4.15.jar
WI-Zoom-1.4-MC1.20.1.jar
wildlife-1.20.1-2.2.jar
woof-4.0.2+1.20.1.jar
wraith-waystones-3.1.2+mc1.20.jar
XaerosWorldMap_1.31.0_Fabric_1.20.jar
Xaeros_Minimap_23.6.0_Fabric_1.20.jar
YamatoGunMod-fabric-0.0.5.jar
yet-another-config-lib-fabric-3.0.3+1.20.jar
your-reputation-0.2.4+jade.1.20.jar
zombiehorsespawn-1.20.1-4.6.jar
```

**Comment by iambatts** [comment] 2023-08-11 02:17
puzzles lib is the issue, dont have any of the other updated mods listed in my modpack, updated puzzles and siphon works again

**Comment by strikerrocker** [comment] 2024-01-03 13:44
Closing as it works again with updated puzzlelib

**Closed as completed by strikerrocker** 2024-01-03 13:44 UTC
