### ISSUE TITLE
causes crash with furn mod with newest update

### ISSUE THREAD

**Issue by jprocket45** [strikerrocker/VanillaTweaks#34] opened 2018-04-21 12:55 UTC
**Vanilla Tweaks Version**:
1.2.11   4/16/2018    
 

**MinecraftForge Version**:
1.12.2 14.23.3.2669
 

**Minecraft Version**:
1.12.2

 

**(Optional) Just Enough Items (JEI) Version**:
none
 

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://pastebin.com/W4jYFdFq
 

**What happens / happened?**:
when loading it crashes says its crayfishes side but if i downgrade a version of tweaks its not a issue just figured to let you know.

 

**How can I reproduce it?**:
just installed 2 mods VanillaTweaks and MrCrayfish's Furniture Mod should crash with most up to date of the 2
 

**(Optional) Mod List**:
MrCrayfishes Furniture Mod    4.2.0.1.12.2
VanillaTweaks    1.2.11

**Comment by Tebreca** [comment] 2018-04-21 13:43
Have you reported it to mrcrayfish's side?
It looks like something is crashing at the capability registry.

I think this really is an error with crayfish's side with the newest version of VT.

But i'll get someone after it who has the actual time to take a closer look.

**Comment by jprocket45** [comment] 2018-04-21 13:51
I have posted this crayfish's side just figured you would have more of a idea since it was your update that started the crash ( not blaming you sorry if that sounds like im pointing at you ) if you can't fix it thats ok I more wanted to let you know and was hoping it was something small on VTs side that could maybe be fixed to stop the crash somehow lol all in all im aware it is something crayfish will half to take care of since the crash actually points at his mod, once again thanks for looking at this though.

**Comment by Tebreca** [comment] 2018-04-21 13:59
As i said, i dont have the time nor the knowledge about this mod to fix it. (i just joined the team) but ill definetly take a look when i have time

**Comment by strikerrocker** [comment] 2018-04-21 13:59
As tebreca said it is caused by crayfish side. But i didnt do anything except few internal refractor in laat few updates if you look at the changelog for it. I will close this issue.

**Closed by strikerrocker** 2018-04-21 13:59 UTC

**Comment by strikerrocker** [comment] 2018-04-22 10:05
@jprocket45 I have added an extra lvl security to reduce the chances of this happening. Can you join my discord https://discord.gg/tqcqeSj I will give you the updated one you can use.
