### ISSUE TITLE
[1.14.4] Duplication bug with Siphon Enchantment. (readmore)

### ISSUE THREAD

**Issue by Gbergz** [strikerrocker/VanillaTweaks#80] opened 2019-12-22 15:27 UTC
**Describe the bug**
When you mine any Block with the Enchantment Siphon on a Pickaxe the mined block get's duplicated. One item drops on the ground the other one gets siphoned like intended.

**To Reproduce** 
1. Have a pickaxe
2. Get the Enchantment 'Siphon' on it.
3. Any block mined will be duplicated.

**Expected behavior**
To not get double the output for mined blocks.

**Screenshots/GIFs**
Look at the Hotbar & then look at the blocks dropping.
GYAZO Link: [https://gyazo.com/474b8c8f8b04e0ae22c797dd3e6c034c](https://gyazo.com/474b8c8f8b04e0ae22c797dd3e6c034c)

**Versions:**(check log if you don't know)
 - Forge Version: 28.1.107
 - MC Version: 1.14.4
 - Mod Version: 1.5.11
 - JEI Version : 6.0.0.26

**Comment by strikerrocker** [comment] 2019-12-23 06:06
Hey can you provide the mod list. This issue seems like a compatibility issue as i cant reproduce it with only vanillatweaks

**Comment by Gbergz** [comment] 2019-12-23 18:32
Hey sorry it took so long to reply, the modlist very long. 
Here it is: [https://gist.github.com/Gbergz/7252666765f7028165b2cf903440aec7](https://gist.github.com/Gbergz/7252666765f7028165b2cf903440aec7)

**Comment by strikerrocker** [comment] 2019-12-23 18:40
Can you find the mod which causes the problem with vt? Best method i know is to run 1st half and check if the bug exists if so its with one of the mods in the 1st half else its in 2nd half. Repeating it can find the mod which is incompatible. If you can't i will do it myself.

**Comment by Gbergz** [comment] 2019-12-23 23:39
I've just gone ahead and done that and i've found what mod causes the duplication bug.
The bug disappeared when i removed the mod [Unstable Tools.](https://www.curseforge.com/minecraft/mc-mods/unstable-tools)

**Comment by strikerrocker** [comment] 2019-12-24 13:47
Hey i have released a temporary fix for this issue. But this means that siphon and blazing enchantment wont work when unstable tools mod is present.

**Comment by Gbergz** [comment] 2019-12-24 15:07
Hey! Thank you. :)

**Closed as completed** 2020-01-24 14:20 UTC
Labels: compatability
