### ISSUE TITLE
Parsing errors when loading built-in advancements + Slime Finder not working

### ISSUE THREAD

**Issue by DefinitelyNotFred** [strikerrocker/VanillaTweaks#32] opened 2018-04-12 21:26 UTC
**Vanilla Tweaks Version**: VanillaTweaks-1.2.9

**MinecraftForge Version**: 14.23.2.2654

**Minecraft Version**: 1.12.2

**Client**

**Crash Report**: https://pastebin.com/YUsQVWUA

**Mod List**: No other mods, although the crash report does include me testing with JEI. Also have tried deleting config files.
 

**What happens?**
I get numerous errors in my logs regarding "parsing errors when loading built-in advancements" whenever a world is loading. I also can't seem to use the Slime Finder: right clicking, left clicking, and doing it in combination with other keys doesn't do anything. I've tried this over a fair distance and have used an online slime chunk finder to make certain that I was in a slime chunk when doing so.

**Comment by strikerrocker** [comment] 2018-04-13 09:15
Hey thanks for reporting this issue. Parsing errors when loading built-in advancements are due to the fact VanillaTweaks remove some default recipes like stone tools , stairs to replace it with better recipes. Due to the fact that advancements are tied to recipes it causes log spam. And finally for the slime finder when you are in a slike chunk have you tried right clicking. It should show whether its slime chunk or not in the action bar. Anyways i am closing this issue until you confirm again. Again thanks for reporting.

**Closed by strikerrocker** 2018-04-13 09:15 UTC

**Comment by DefinitelyNotFred** [comment] 2018-04-13 20:56
Oh, so it does. Now that I see it, it seems so obvious. Maybe you should change the text color to something a little more bold. The white text is hard to see against sand.

**Comment by strikerrocker** [comment] 2018-04-13 20:57
I will see about it in the next update. Again thanks for reporting. I hope I can remove the log spam caused by vanillatweaks in 1.13

**Comment by strikerrocker** [comment] 2018-04-13 20:59
Also if you are in discord I have a discord server of my own : https://discord.gg/tqcqeSj

**Comment by DefinitelyNotFred** [comment] 2018-04-15 04:59
Probably a cyan color would be the best option.
