### ISSUE TITLE
Conflict with RealBench: Crafting Pad deletes items

### ISSUE THREAD

**Issue by IChris2698I** [strikerrocker/VanillaTweaks#66] opened 2019-09-02 12:55 UTC
**Vanilla Tweaks Version**:
1.12.2-1.5.4

**MinecraftForge Version**:
14.23.5.2768

**Minecraft Version**:
1.12.2

**(Optional) Just Enough Items (JEI) Version**:
Not Installed, though it does happen with JEI installed as well.

**(Optional) Baubles Version**: 
Not Installed, though it does happen with Baubles 1.12-1.5.2 installed as well.

**Client or Server?**:
- [X] Client (happens in a single player world)
- [X] Server (also happens on a server my friend is hosting)

**Crash Report (via. [Hastebin](http://hastebin.com/))**:
Does not crash. Though there is a log from RealBench [injecting into a couple things](https://hastebin.com/osavuqunak.css), might or might not help.

**What happens / happened?**:
I left an item in the Crafting Pad and pressed Escape to close it. The item was deleted.

**How can the issue be reproduced?**:
1. Create a new world with the seed `blue`
1. Break 2 logs.
1. Make a Crafting Pad.
1. Put the Crafting Pad on your hotbar. Slot does not matter.
1. Open the Crafting Pad.
1. Put a stick or plank in the Crafting Pad. Slot does not matter.
1. Press Escape to close the Crafting Pad.
1. Item should be returned to your inventory, but is deleted instead.

** Mod List**:
* RealBench-1.12.2-1.3.3
* Vanilla Tweaks

** Comments**:
I hope there's an API call you can make, a property you can define, or a GUI / inventory you can save and reuse the next time the Crafting Pad is opened.

It sounds like other hand-held crafting tables are affected too. There's a comment on the RealBench CurseForge page about [the same thing happening](https://www.curseforge.com/minecraft/mc-mods/realbench?comment=57) with the Portable Crafting Bench from the Random Things mod, though I haven't checked if that's still happening.

I wanted to file an issue about this on the RealBench issue page as well, but [their issue page is down](https://gitlab.prok.pw/Prototik/RealBench/issues).

**Comment by strikerrocker** [comment] 2019-09-02 13:12
Looks like the RealBench mod is modifying the vanilla crafting table so it holds its contents when the gui is closed. The author seems inactive and its source code isn't available. Essentially VanillaTweaks extends Vanilla crafting table for its crafting pad. The issue can be fixed by RealBench or by a clustered way of duplicating vanilla code. I would rather not do it the second way.

**Comment by strikerrocker** [comment] 2019-09-02 13:22
I have let a message to the author of RealBench proposing a fix. Will have to see if he responds. Until that i suppose you can remove that mod?

**Comment by IChris2698I** [comment] 2019-09-02 13:35
Thank you for the quick response. We'll see when/if the RealBench author responds. In the mean time, I'll probably be careful and just cheat back in anything I end up losing; Life in the Village isn't a tough modpack, where things take many crafting steps and lots of materials to make.

**Comment by strikerrocker** [comment] 2019-10-05 12:51
There is no way to fix this issue in my side thus i am closing this.

**Closed as completed by strikerrocker** 2019-10-05 12:51 UTC
Labels: compatability

**Comment by raidenc04** [comment] 2019-11-04 07:08
I'm as well getting this error although, I do not currently have the RealBench mod loaded into the pack I am playing, and I do not know what is causing this problem.

**Comment by strikerrocker** [comment] 2019-11-04 11:02
Hey can you provide me the mod list of the pack. I will try reproducing the issue.

**Comment by raidenc04** [comment] 2019-11-05 01:40
https://www.curseforge.com/minecraft/modpacks/performance-craft/relations/dependencies
