### ISSUE TITLE
Crash on startup 1.42 2

### ISSUE THREAD

**Issue by TmeansTERMINATOR** [strikerrocker/VanillaTweaks#44] opened 2018-12-25 10:01 UTC
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2018-12-25
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Vanilla Tweaks (vt)
Caused by: java.lang.NoSuchMethodError: io.github.strikerrocker.vt.items.ItemCraftingPad.setTranslationKey(Ljava/lang/String;)Lnet/minecraft/item/Item;
    at io.github.strikerrocker.vt.items.ItemCraftingPad.<init>(ItemCraftingPad.java:21)
    at io.github.strikerrocker.vt.items.VTItems.<clinit>(VTItems.java:23)
    at io.github.strikerrocker.vt.VT.onPreInit(VT.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 293763640 bytes (280 MB) / 787775488 bytes (751 MB) up to 3719561216 bytes (3547 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx3560M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 124 mods loaded, 124 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                 | Version              | Source                                              | Signature                                |
       |:----- |:---------------------------------- |:-------------------- |:--------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                          | 1.12.2               | minecraft.jar                                       | None                                     |
       | LCH   | mcp                                | 9.42                 | minecraft.jar                                       | None                                     |
       | LCH   | FML                                | 8.0.99.99            | forge-1.12.2-14.23.5.2796.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                              | 14.23.5.2796         | forge-1.12.2-14.23.5.2796.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy                  | 1.0.0                | minecraft.jar                                       | None                                     |
       | LCH   | itemphysic                         | 1.4.0                | minecraft.jar                                       | None                                     |
       | LCH   | micdoodlecore                      |                      | minecraft.jar                                       | None                                     |
       | LCH   | foamfixcore                        | 7.7.4                | minecraft.jar                                       | None                                     |
       | LCH   | dsurroundcore                      | 3.5.4.0              | minecraft.jar                                       | None                                     |
       | LCH   | randompatches                      | 1.12.2-1.11.0.1      | randompatches-1.12.2-1.11.0.1.jar                   | None                                     |
       | LCH   | versionchecker                     | @VERSION@            | [1.12.2]+VersionChecker-1.4.0.jar                   | None                                     |
       | LCH   | uncraftingtable                    | 1.8-beta6            | [1.12]UncraftingTable-1.8-beta6.jar                 | None                                     |
       | LCH   | codechickenlib                     | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | ancientwarfare                     | 1.12.2-2.7.0.497     | ancientwarfare-1.12.2-2.7.0.497.jar                 | None                                     |
       | LCH   | ancientwarfarestructure            | @VERSION@            | ancientwarfare-1.12.2-2.7.0.497.jar                 | None                                     |
       | LCH   | ancientwarfarevehicle              | 1.12.2-2.7.0.497     | ancientwarfare-1.12.2-2.7.0.497.jar                 | None                                     |
       | LCH   | ancientwarfarenpc                  | 1.12.2-2.7.0.497     | ancientwarfare-1.12.2-2.7.0.497.jar                 | None                                     |
       | LCH   | ancientwarfareautomation           | 1.12.2-2.7.0.497     | ancientwarfare-1.12.2-2.7.0.497.jar                 | None                                     |
       | LCH   | backpacks16840                     | 3.5.4                | backpacks+1.12.2+-+3.5.4.jar                        | None                                     |
       | LCH   | badwithernocookiereloaded          | 1.12.2-3.3.16        | badwithernocookiereloaded-1.12.2-3.3.16.jar         | None                                     |
       | LCH   | betteradvancements                 | 0.0.14.68            | BetterAdvancements-1.12.2-0.0.14.68.jar             | None                                     |
       | LCH   | betteranimalsplus                  | 4.0.1                | betteranimalsplus-4.0.1.jar                         | None                                     |
       | LCH   | betterthanmending                  | 1.1.1                | BetterThanMending-1.1.1.jar                         | None                                     |
       | LCH   | bibliocraft                        | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                   | None                                     |
       | LCH   | bookshelf                          | 2.3.570              | Bookshelf-1.12.2-2.3.570.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | carryon                            | 1.12.1               | CarryOn+MC1.12.2+v1.12.1.jar                        | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCH   | ceanimals                          | 1.4.1                | ceanimals-1.12.2-1.4.1.jar                          | None                                     |
       | LCH   | chameleon                          | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                            | None                                     |
       | LCH   | champions                          | 1.12.2-0.8-beta      | champions-1.12.2-0.8-beta.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | chickenchunks                      | 2.4.1.73             | ChickenChunks-1.12.2-2.4.1.73-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | christmasfestivity                 | 1.2.1.5              | ChristmasFestivityMod-1.12.2-1.2.1.5.jar            | None                                     |
       | LCH   | chunkanimator                      | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                        | None                                     |
       | LCH   | toughasnails                       | 3.1.0.138            | ToughAsNails-1.12.2-3.1.0.138-universal.jar         | None                                     |
       | LCH   | comforts                           | 1.4.1.1              | comforts-1.12.2-1.4.1.1.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | consecration                       | 0.0.14               | consecration-1.12.2-0.0.14.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | configmod                          | v1.0                 | coroutil-1.12.1-1.2.15.jar                          | None                                     |
       | LCH   | extendedrenderer                   | v1.0                 | coroutil-1.12.1-1.2.15.jar                          | None                                     |
       | LCH   | coroutil                           | 1.12.1-1.2.15        | coroutil-1.12.1-1.2.15.jar                          | None                                     |
       | LCH   | creativecore                       | 1.9.9                | CreativeCore_v1.9.35_mc1.12.2.jar                   | None                                     |
       | LCH   | cyberware                          | 0.2.10.15            | cyberware-1.12.2-0.2.10.15.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | LCH   | dungeonmobs                        | 5.5.3                | dungeonmobs-5.5.3-MC1.12.2.jar                      | None                                     |
       | LCH   | dynamicstealth                     | 1.12.2.007           | DynamicStealth-1.12.2.007.jar                       | None                                     |
       | LCH   | eplus                              | 5.0.175              | EnchantingPlus-1.12.2-5.0.175.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | csb_ench_table                     | 1.1.3                | EnchantingTable-1.12-1.1.3.jar                      | None                                     |
       | LCH   | expcraft                           | 1.3.0                | ExpCraft-1.12.2_v1.3.0.jar                          | None                                     |
       | LCH   | extrautils2                        | 1.0                  | extrautils2-1.12-1.9.8.jar                          | None                                     |
       | LCH   | fastfurnace                        | 1.2.1                | FastFurnace-1.12.2-1.2.1.jar                        | None                                     |
       | LCH   | fastbench                          | 1.6.0                | FastWorkbench-1.12.2-1.6.0.jar                      | None                                     |
       | LCH   | foamfix                            | 0.10.3-1.12.2        | foamfix-0.10.3-1.12.2.jar                           | None                                     |
       | LCH   | forgemultipartcbe                  | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | microblockcbe                      | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | LCH   | minecraftmultipartcbe              | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | LCH   | futureminecraft                    | 1.1.2.1              | FutureMincraftV1.1.2.1.jar                          | None                                     |
       | LCH   | ic2                                | 2.8.105-ex112        | industrialcraft-2-2.8.105-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCH   | galacticraftcore                   | 4.0.1.181            | GalacticraftCore-1.12.2-4.0.1.181.jar               | None                                     |
       | LCH   | galacticraftplanets                | 4.0.1.181            | Galacticraft-Planets-1.12.2-4.0.1.181.jar           | None                                     |
       | LCH   | gokistats                          | @version@            | gokiStats-1.2.5.1.jar                               | None                                     |
       | LCH   | hammercore                         | 2.0.4.1              | HammerCore-1.12.2-2.0.4.1.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | harvest                            | 1.12-1.2.7-20        | Harvest-1.12-1.2.7-20.jar                           | None                                     |
       | LCH   | speedsterheroes                    | 1.12.2-2.0.10        | SpeedsterHeroes-1.12.2-2.0.10.jar                   | None                                     |
       | LCH   | lucraftcore                        | 1.12.2-2.3.2         | LucraftCore-1.12.2-2.3.2.jar                        | None                                     |
       | LCH   | heroesexpansion                    | 1.12.2-1.2.1         | HeroesExpansion-1.12.2-1.2.1.jar                    | None                                     |
       | LCH   | hw_inv                             | 1.12.1-1.0.1         | hostileworlds_invasions-1.12.1-1.0.1.jar            | None                                     |
       | LCH   | waila                              | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
       | LCH   | iblis                              | 1.0.9                | iblis-headshots-1.0.9.jar                           | None                                     |
       | LCH   | ichunutil                          | 7.1.4                | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
       | LCH   | improvableskills                   | 3.5.9r               | ImprovableSkills-1.12.2-3.5.9r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | infernalmobs                       | 1.7.5                | InfernalMobs-1.12.2.jar                             | None                                     |
       | LCH   | inventorytweaks                    | 1.64+dev.144.88fda94 | InventoryTweaks-1.64+dev.144.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | jei                                | 4.14.3.241           | jei_1.12.2-4.14.3.241.jar                           | None                                     |
       | LCH   | journeymap                         | 1.12.2-5.5.3         | journeymap-1.12.2-5.5.3.jar                         | None                                     |
       | LCH   | jeresources                        | 0.8.10.50            | JustEnoughResources-1.12.2-0.8.10.50.jar            | None                                     |
       | LCH   | lex                                | 1.0.8                | LibEx-1.12.2-1.0.8.jar                              | None                                     |
       | LCH   | lightningtweaks                    | 1.12.2-1.1.3.1       | lightningtweaks-1.12.2-1.1.3.1.jar                  | None                                     |
       | LCH   | lootbags                           | 2.5.7                | LootBags-1.12.2-2.5.7.jar                           | None                                     |
       | LCH   | lunatriuscore                      | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar         | None                                     |
       | LCH   | macrokey                           | 1.12.2-1.1.6.3       | MacroKey-1.12.2-1.1.6.3.jar                         | None                                     |
       | LCH   | mobamputation                      | 7.0.0                | MobAmputation-1.12.2-7.0.0.jar                      | None                                     |
       | LCH   | mousetweaks                        | 2.9                  | MouseTweaks-2.9-mc1.12.2.jar                        | None                                     |
       | LCH   | multimine                          | 1.6.0                | MultiMine-1.12.2.jar                                | None                                     |
       | LCH   | multimob                           | 1.0.2                | multimob-1.0.2.jar                                  | None                                     |
       | LCH   | nex                                | 2.0.8                | NetherEx-1.12.2-2.0.8.jar                           | None                                     |
       | LCH   | netherportalfix                    | 5.3.17               | NetherPortalFix_1.12.1-5.3.17.jar                   | None                                     |
       | LCH   | nodami                             | 0.5                  | nodami-1.12.2-0.5.jar                               | None                                     |
       | LCH   | omlib                              | 3.0.1-162            | omlib-1.12.2-3.0.1-162.jar                          | None                                     |
       | LCH   | openmodularturrets                 | 3.0.1-264            | openmodularturrets-1.12.2-3.0.1-264.jar             | None                                     |
       | LCH   | oreexcavation                      | 1.4.133              | OreExcavation-1.4.133.jar                           | None                                     |
       | LCH   | outfox                             | 0.1.3                | outfox-0.1.3-mc1.12.2.jar                           | None                                     |
       | LCH   | prettybeaches                      | 1.0.4                | PrettyBeaches_1.12.2-1.0.4.jar                      | None                                     |
       | LCH   | primitivemobs                      | 1.2                  | primitivemobs-1.2.jar                               | None                                     |
       | LCH   | progressivebosses                  | 1.4.0                | ProgressiveBosses-1.4.0-mc1.12.x.jar                | None                                     |
       | LCH   | quickleafdecay                     | 1.2.4                | QuickLeafDecay-MC1.12.1-1.2.4.jar                   | None                                     |
       | LCH   | randomtweaks                       | 1.12.2-2.4.0.2       | randomtweaks-1.12.2-2.4.0.2.jar                     | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCH   | silentlib                          | 3.0.10               | SilentLib-1.12.2-3.0.10-161.jar                     | None                                     |
       | LCH   | scalinghealth                      | 1.3.31               | ScalingHealth-1.12.2-1.3.31-132.jar                 | None                                     |
       | LCH   | sereneseasons                      | 1.2.15               | SereneSeasons-1.12.2-1.2.15-universal.jar           | None                                     |
       | LCH   | slurpiesdongles                    | 2.1.5.8.1            | Slurpie's+Dongles-1.12,+1.12.1,++1.12.2-2.17.3.jar  | None                                     |
       | LCH   | smarthoppers                       | 4.1.5                | smarthoppers-mc1.12.2-4.1.5.jar                     | None                                     |
       | LCH   | soundfilters                       | 0.10_for_1.12        | SoundFilters-0.10_for_1.12.jar                      | None                                     |
       | LCH   | stackie                            | 1.6.0.48             | Stackie-1.12.2-1.6.0.48-universal.jar               | None                                     |
       | LCH   | stg                                | 1.11.2-1.1.2         | stg-1.11.2-1.1.2.jar                                | None                                     |
       | LCH   | storagedrawers                     | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                     | None                                     |
       | LCH   | surge                              | 2.0.76               | Surge-1.12.2-2.0.76.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | survivaltweaks                     | 5.1.0                | SurvivalTweaks-5.1.1-1.12.2.jar                     | None                                     |
       | LCH   | sync                               | 7.0.2                | Sync-1.12.2-7.0.2.jar                               | None                                     |
       | LCH   | themodthatletsyoupunchwooloffsheep | 1.1.0                | TheModThatLetsYouPunchWoolOffSheep-1.12.2-1.1.0.jar | None                                     |
       | LCH   | tickratechanger                    | 1.0.14               | TickrateChanger-1.0.14.jar                          | None                                     |
       | LCH   | toolbelt                           | 1.7.1                | ToolBelt-1.12.0-1.7.1.jar                           | None                                     |
       | LCH   | twilightforest                     | 3.8.689              | twilightforest-1.12.2-3.8.689-universal.jar         | None                                     |
       | LCH   | upsizer                            | 4.0.1                | upsizer-mc1.12-4.0.1.jar                            | None                                     |
       | LCH   | va                                 | 1.12.2-1.5.3         | va-1.12.2-1.5.5.jar                                 | None                                     |
       | LCH   | vanillafix                         | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar                            | None                                     |
       | LCH   | vanillafoodpantry                  | 4.3.0                | vanillafoodpantry-mc1.12.2-4.3.jar                  | None                                     |
       | LCH   | visuals                            | 2r                   | Visuals-1.12.2-2r.jar                               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | wailaharvestability                | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar               | None                                     |
       | LCH   | walljump                           | 1.12.2-1.2.1         | walljump-1.12.2-1.2.1.jar                           | None                                     |
       | LCH   | wanionlib                          | 1.12.2-1.9           | WanionLib-1.12.2-1.9.jar                            | None                                     |
       | LCH   | wawla                              | 2.5.265              | Wawla-1.12.2-2.5.265.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | wrcbe                              | 2.3.1                | WR-CBE-1.12.2-2.3.1.30-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | orelib                             | 3.5.1.3              | OreLib-1.12.2-3.5.1.3BETA.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                          | 3.5.4.0              | DynamicSurroundings-1.12.2-3.5.4.0BETA.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dshuds                             | 3.5.4.0              | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCE   | vt                                 | 1.4.2                | VanillaTweaks-1.4.2.jar                             | None                                     |
       | LC    | unidict                            | 1.12.2-2.9.1         | UniDict-1.12.2-2.9.1.jar                            | None                                     |
  Loaded coremods (and transformers): ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.144.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.0BETA.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      HCASM (HammerCore-1.12.2-2.0.4.1.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.76.jar)
                                        
                                      TickrateChanger (TickrateChanger-1.0.14.jar)
                                        me.guichaguri.tickratechanger.TickrateTransformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
                                        brad16840.core.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.2.jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      RandomPatches (randompatches-1.12.2-1.11.0.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.16' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 302 names; 343 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Improvable Skills (improvableskills) @3.5.9r
                               -Visuals (visuals) @2r
  Suspected Mods: Vanilla Tweaks (vt)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2796
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.16, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, file/Faithful 1.12.2 64 (incompatible)
  Current Language: English
  Profiler Position: N/A (disabled)
  CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by strikerrocker** [comment] 2018-12-25 14:39
Duplicate of #43

**Closed as completed by strikerrocker** 2018-12-25 14:39 UTC
Labels: duplicate
