### ISSUE TITLE
[Forge 1.18.1] Silktouch Spawners convert to pig spawners

### ISSUE THREAD

**Issue by itsdinkd** [strikerrocker/VanillaTweaks#155] opened 2022-01-09 06:51 UTC
As title suggests, when silk touching a spawner, say a enderman spawner or wither skeleton spawner, it always turns into a Pig Spawner. This is true for any type of spawner you silk touch.

**Comment by strikerrocker** [comment] 2022-01-10 06:45
Can you say which version of the mod is this? I can't reproduce this issue in the latest version.

**Comment by itsdinkd** [comment] 2022-01-10 09:14
I am not near a computer but it's the most recent version of vanilla tweaks
on curseforge for 1.18.1 forge

**Comment by strikerrocker** [comment] 2022-01-10 12:39
I can't reproduce this issue on the latest. I need to the exact version to check and fix this issue if it exists. Also make sure this is only caused by VanillaTweaks alone present with forge and not any other mod.

**Comment by strikerrocker** [comment] 2022-01-12 11:39
> I am not near a computer but it's the most recent version of vanilla tweaks
> on curseforge for 1.18.1 forge

Any updates on the exact version?

**Comment by itsdinkd** [comment] 2022-01-13 17:54
like i mentioned, the latest version out on curseforge 

![image](https://user-images.githubusercontent.com/35115304/149383264-f8a3cb70-8210-4dab-b5fb-574505874017.png)

**Comment by strikerrocker** [comment] 2022-01-13 18:11
Is there any other mod installed bcoz I can't get with only VanillaTweaks to reproduce this.

**Comment by JosueD99** [comment] 2022-01-16 04:50
I have this issue also. Let me clarify, upon silk touching the spawner I do indeed get the spawner with the correct entity tag. BUT, when I go to place the spawner in the world, it reverts to a pig spawner. I am playing on a server, it only functions when I am a server Operator. Is there a way to fix this so you do not need to be Opped for it to be placed?

**Comment by strikerrocker** [comment] 2022-01-16 06:24
@JosueD99 Do you have any other mod other than VanillaTweaks installed if so please give me the list, as I can't reproduce with VanillaTweaks alone present in a server with player being not OP.

**Comment by JosueD99** [comment] 2022-01-16 06:47
These are ALL the mods installed on the client and/or server:
appleskins
applied energistics 2
balm
bow infinity
collective
crafting tweaks
cycle paintings
dynmap
gravestone
infinity mending
jade
jei
just enough keys
ma essentials
mouse tweaks
optifine
ore excavation
reap
sleeping bags
solar energy
sophisticated backpacks
storage drawers
vanilla tweaks
voice chat
worldedit

**Comment by strikerrocker** [comment] 2022-01-16 07:30
If you are free can you drop in my discord to debug this issue? Discord link https://discord.com/invite/tqcqeSj

**Comment by strikerrocker** [comment] 2022-01-16 08:44
Tried with the given mods still couldn't reproduce this. If anyone has a reproducible test case for this please provide with VT alone or with VT and the conflicting mod.

**Comment by AbsolemJackdaw** [comment] 2022-01-16 08:49
Sounds like there is a permission mod somewhere messing with the perms of placing down blocks, given it only happens for non-operator players. The code for breaking and placing spawner blocks in vanilla tweaks does not contain any of those checks.

**Comment by strikerrocker** [comment] 2022-03-10 18:10
Can't reproduce this issue without any luck so closing.

**Closed as completed by strikerrocker** 2022-03-10 18:10 UTC
